"""update

Revision ID: c723fcf829c8
Revises: 
Create Date: 2025-11-01 13:50:06.592532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c723fcf829c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_tariff_plans',
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.String(
                        length=500), nullable=True),
                    sa.Column('max_employees', sa.Integer(), nullable=True),
                    sa.Column('max_verifications_per_month',
                              sa.Integer(), nullable=True),
                    sa.Column('max_orders_per_month',
                              sa.Integer(), nullable=True),
                    sa.Column('auto_manufacture_year',
                              sa.Boolean(), nullable=False),
                    sa.Column('auto_teams', sa.Boolean(), nullable=False),
                    sa.Column('auto_metrolog', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title')
                    )
    op.create_index(op.f('ix_base_tariff_plans_id'),
                    'base_tariff_plans', ['id'], unique=False)
    op.create_table('calendar_reports',
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('dispatcher', sa.Boolean(), nullable=True),
                    sa.Column('route', sa.Boolean(), nullable=True),
                    sa.Column('no_date', sa.Boolean(), nullable=True),
                    sa.Column('date', sa.Boolean(), nullable=True),
                    sa.Column('address', sa.Boolean(), nullable=True),
                    sa.Column('phone_number', sa.Boolean(), nullable=True),
                    sa.Column('sec_phone_number', sa.Boolean(), nullable=True),
                    sa.Column('client_full_name', sa.Boolean(), nullable=True),
                    sa.Column('legal_entity', sa.Boolean(), nullable=True),
                    sa.Column('counter_number', sa.Boolean(), nullable=True),
                    sa.Column('water_type', sa.Boolean(), nullable=True),
                    sa.Column('price', sa.Boolean(), nullable=True),
                    sa.Column('status', sa.Boolean(), nullable=True),
                    sa.Column('additional_info', sa.Boolean(), nullable=True),
                    sa.Column('for_auditor', sa.Boolean(), nullable=True),
                    sa.Column('for_dispatcher1', sa.Boolean(), nullable=True),
                    sa.Column('for_dispatcher2', sa.Boolean(), nullable=True),
                    sa.Column('date_of_get', sa.Boolean(), nullable=True),
                    sa.Column('deleted_at', sa.Boolean(), nullable=True),
                    sa.Column('fields_order', sa.String(), nullable=True),
                    sa.Column('company_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['companies.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_calendar_reports_id'),
                    'calendar_reports', ['id'], unique=False)
    op.create_table('company_tariff_history',
                    sa.Column('company_id', sa.Integer(), nullable=False),
                    sa.Column('valid_from', sa.Date(), nullable=False),
                    sa.Column('valid_to', sa.Date(), nullable=True),
                    sa.Column('max_employees', sa.Integer(), nullable=True),
                    sa.Column('monthly_verifications',
                              sa.Integer(), nullable=True),
                    sa.Column('monthly_orders', sa.Integer(), nullable=True),
                    sa.Column('auto_manufacture_year',
                              sa.Boolean(), nullable=False),
                    sa.Column('auto_teams', sa.Boolean(), nullable=False),
                    sa.Column('auto_metrolog', sa.Boolean(), nullable=False),
                    sa.Column('reason', sa.String(length=255), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['companies.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_company_tariff_history_company_id'),
                    'company_tariff_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_tariff_history_created_at'),
                    'company_tariff_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_tariff_history_id'),
                    'company_tariff_history', ['id'], unique=False)
    op.create_index(op.f('ix_company_tariff_history_is_active'),
                    'company_tariff_history', ['is_active'], unique=False)
    op.create_table('company_tariff_state',
                    sa.Column('company_id', sa.Integer(), nullable=False),
                    sa.Column('valid_from', sa.Date(), nullable=False),
                    sa.Column('valid_to', sa.Date(), nullable=True),
                    sa.Column('max_employees', sa.Integer(), nullable=True),
                    sa.Column('max_verifications',
                              sa.Integer(), nullable=True),
                    sa.Column('max_orders', sa.Integer(), nullable=True),
                    sa.Column('used_employees', sa.Integer(), nullable=False),
                    sa.Column('used_verifications',
                              sa.Integer(), nullable=False),
                    sa.Column('used_orders', sa.Integer(), nullable=False),
                    sa.Column('carry_over_verifications',
                              sa.Boolean(), nullable=False),
                    sa.Column('carry_over_orders',
                              sa.Boolean(), nullable=False),
                    sa.Column('auto_manufacture_year',
                              sa.Boolean(), nullable=False),
                    sa.Column('auto_teams', sa.Boolean(), nullable=False),
                    sa.Column('auto_metrolog', sa.Boolean(), nullable=False),
                    sa.Column('last_tariff_history_id',
                              sa.Integer(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['company_id'], ['companies.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['last_tariff_history_id'], [
                        'company_tariff_history.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_company_tariff_state_company_id'),
                    'company_tariff_state', ['company_id'], unique=True)
    op.create_index(op.f('ix_company_tariff_state_id'),
                    'company_tariff_state', ['id'], unique=False)
    op.create_index(op.f('ix_company_tariff_state_last_tariff_history_id'),
                    'company_tariff_state', ['last_tariff_history_id'], unique=False)
    op.alter_column('act_numbers', 'act_number',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('act_numbers', 'address',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('act_numbers', 'verification_date',
                    existing_type=sa.DATE(),
                    nullable=False)
    op.alter_column('act_numbers', 'legal_entity',
                    existing_type=sa.TEXT(),
                    type_=sa.Enum('individual', 'legal',
                                  name='verification_legal_entity_enum'),
                    nullable=False,
                    postgresql_using='legal_entity::verification_legal_entity_enum')
    op.alter_column('act_numbers', 'count',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('act_numbers', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.create_unique_constraint('uq_act_number_company_series', 'act_numbers', [
                                'act_number', 'company_id', 'series_id'])
    op.drop_constraint('act_numbers_city_id_fkey',
                       'act_numbers', type_='foreignkey')
    op.drop_constraint('act_numbers_series_id_fkey',
                       'act_numbers', type_='foreignkey')
    op.drop_constraint('act_numbers_company_id_fkey',
                       'act_numbers', type_='foreignkey')
    op.create_foreign_key(None, 'act_numbers', 'series', [
                          'series_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'act_numbers', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'act_numbers', 'cities', [
                          'city_id'], ['id'], ondelete='SET NULL')
    op.alter_column('appeals', 'status',
                    existing_type=sa.TEXT(),
                    type_=sa.Enum('accepted', 'in_progress',
                                  'done', name='appeal_status_enum'),
                    nullable=False,
                    postgresql_using='status::appeal_status_enum')
    op.alter_column('appeals', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('appeals_company_id_fkey',
                       'appeals', type_='foreignkey')
    op.drop_constraint('appeals_dispatcher_id_fkey',
                       'appeals', type_='foreignkey')
    op.create_foreign_key(None, 'appeals', 'employees', [
                          'dispatcher_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'appeals', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('cities', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('cities_company_id_fkey', 'cities', type_='foreignkey')
    op.create_foreign_key(None, 'cities', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_company_activities_id'),
                    'company_activities', ['id'], unique=False)
    op.drop_constraint('company_activities_company_id_fkey',
                       'company_activities', type_='foreignkey')
    op.create_foreign_key(None, 'company_activities', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('company_calendar_day_info', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('company_calendar_day_info_company_id_fkey',
                       'company_calendar_day_info', type_='foreignkey')
    op.create_foreign_key(None, 'company_calendar_day_info', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.add_column('company_reports', sa.Column(
        'fields_order', sa.String(), nullable=True))
    op.alter_column('company_reports', 'name',
                    existing_type=sa.VARCHAR(length=60),
                    type_=sa.String(length=100),
                    nullable=False)
    op.alter_column('company_reports', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('company_reports_company_id_fkey',
                       'company_reports', type_='foreignkey')
    op.create_foreign_key(None, 'company_reports', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('company_reports', 'is_deleted')
    op.create_index(op.f('ix_company_si_types_id'),
                    'company_si_types', ['id'], unique=False)
    op.drop_constraint('company_si_types_company_id_fkey',
                       'company_si_types', type_='foreignkey')
    op.create_foreign_key(None, 'company_si_types', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('counter_assignments_order_id_fkey',
                       'counter_assignments', type_='foreignkey')
    op.drop_constraint('counter_assignments_employee_id_fkey',
                       'counter_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'counter_assignments', 'employees', [
                          'employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'counter_assignments', 'orders', [
                          'order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('employees', 'status',
                    existing_type=sa.VARCHAR(length=30),
                    type_=sa.Enum('admin', 'director', 'auditor', 'dispatcher1',
                                  'dispatcher2', 'verifier', name='employee_status_enum'),
                    existing_nullable=False,
                    postgresql_using='status::employee_status_enum')
    op.drop_constraint('employees_default_city_id_fkey',
                       'employees', type_='foreignkey')
    op.drop_constraint('employees_default_verifier_id_fkey',
                       'employees', type_='foreignkey')
    op.drop_constraint('employees_series_id_fkey',
                       'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'verifiers', [
                          'default_verifier_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'employees', 'series', [
                          'series_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'employees', 'cities', [
                          'default_city_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('employees_cities_employee_id_fkey',
                       'employees_cities', type_='foreignkey')
    op.drop_constraint('employees_cities_city_id_fkey',
                       'employees_cities', type_='foreignkey')
    op.create_foreign_key(None, 'employees_cities', 'cities', [
                          'city_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'employees_cities', 'employees', [
                          'employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('employees_companies_company_id_fkey',
                       'employees_companies', type_='foreignkey')
    op.drop_constraint('employees_companies_employee_id_fkey',
                       'employees_companies', type_='foreignkey')
    op.create_foreign_key(None, 'employees_companies', 'employees', [
                          'employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'employees_companies', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('employees_routes_route_id_fkey',
                       'employees_routes', type_='foreignkey')
    op.drop_constraint('employees_routes_employee_id_fkey',
                       'employees_routes', type_='foreignkey')
    op.create_foreign_key(None, 'employees_routes', 'routes', [
                          'route_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'employees_routes', 'employees', [
                          'employee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('equipment_info', 'type',
                    existing_type=sa.VARCHAR(length=30),
                    type_=sa.Enum('maintenance', 'verification',
                                  name='equipment_info_type_enum'),
                    nullable=False,
                    postgresql_using='type::equipment_info_type_enum')
    op.alter_column('equipment_info', 'date_from',
                    existing_type=sa.DATE(),
                    nullable=False)
    op.alter_column('equipment_info', 'date_to',
                    existing_type=sa.DATE(),
                    nullable=False)
    op.alter_column('equipments', 'type',
                    existing_type=sa.VARCHAR(length=120),
                    type_=sa.Enum('standard', 'measurement', 'auxiliary',
                                  'other', name='equipment_type_enum'),
                    existing_nullable=False,
                    postgresql_using='type::equipment_type_enum')
    op.drop_constraint('equipments_activity_id_fkey',
                       'equipments', type_='foreignkey')
    op.drop_constraint('equipments_si_type_id_fkey',
                       'equipments', type_='foreignkey')
    op.drop_constraint('equipments_company_id_fkey',
                       'equipments', type_='foreignkey')
    op.create_foreign_key(None, 'equipments', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'equipments', 'company_si_types', [
                          'si_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'equipments', 'company_activities', [
                          'activity_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('equipments_verifiers_verifier_id_fkey',
                       'equipments_verifiers', type_='foreignkey')
    op.drop_constraint('equipments_verifiers_equipment_id_fkey',
                       'equipments_verifiers', type_='foreignkey')
    op.create_foreign_key(None, 'equipments_verifiers', 'equipments', [
                          'equipment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'equipments_verifiers', 'verifiers', [
                          'verifier_id'], ['id'], ondelete='CASCADE')
    op.alter_column('locations', 'name',
                    existing_type=sa.VARCHAR(length=60),
                    nullable=False)
    op.alter_column('locations', 'count',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('locations', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('locations_company_id_fkey',
                       'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('methods', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('methods_company_id_fkey',
                       'methods', type_='foreignkey')
    op.create_foreign_key(None, 'methods', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.add_column('metrologs_info', sa.Column(
        'before_water_temperature', sa.Float(), nullable=True))
    op.add_column('metrologs_info', sa.Column(
        'before_air_temperature', sa.Float(), nullable=True))
    op.add_column('metrologs_info', sa.Column(
        'before_humdity', sa.Float(), nullable=True))
    op.add_column('metrologs_info', sa.Column(
        'before_pressure', sa.Integer(), nullable=True))
    op.alter_column('metrologs_info', 'verification_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('metrologs_info', 'company_id',
                    existing_type=sa.BIGINT(),
                    type_=sa.Integer(),
                    existing_nullable=False)
    op.drop_constraint('metrologs_info_verification_id_fkey',
                       'metrologs_info', type_='foreignkey')
    op.drop_constraint('fk_metrologs_info_company',
                       'metrologs_info', type_='foreignkey')
    op.create_foreign_key(None, 'metrologs_info', 'verification_entries', [
                          'verification_id'], ['id'], ondelete='CASCADE')
    op.drop_column('metrologs_info', 'befor_air_temperature')
    op.drop_column('metrologs_info', 'befor_water_temperature')
    op.drop_column('metrologs_info', 'befor_pressure')
    op.drop_column('metrologs_info', 'befor_humdity')
    op.alter_column('orders', 'address',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('orders', 'phone_number',
                    existing_type=sa.VARCHAR(length=18),
                    nullable=False)
    op.alter_column('orders', 'legal_entity',
                    existing_type=sa.TEXT(),
                    type_=sa.Enum('individual', 'legal',
                                  name='verification_legal_entity_enum'),
                    existing_nullable=True,
                    postgresql_using='legal_entity::verification_legal_entity_enum')
    op.alter_column('orders', 'counter_number',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('orders', 'water_type',
                    existing_type=sa.VARCHAR(length=30),
                    type_=sa.Enum('cold', 'hot', 'cold_hot',
                                  'unnamed', name='order_water_type_enum'),
                    nullable=False,
                    postgresql_using='water_type::order_water_type_enum')
    op.alter_column('orders', 'status',
                    existing_type=sa.TEXT(),
                    type_=sa.Enum('pending', 'approved',
                                  name='order_status_enum'),
                    nullable=False,
                    postgresql_using='status::order_status_enum')
    op.alter_column('orders', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('orders_company_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_dispatcher_id_fkey',
                       'orders', type_='foreignkey')
    op.drop_constraint('orders_city_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_route_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'cities', [
                          'city_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'routes', [
                          'route_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'employees', [
                          'dispatcher_id'], ['id'], ondelete='SET NULL')
    op.alter_column('reasons', 'type',
                    existing_type=sa.VARCHAR(length=20),
                    type_=sa.Enum('p_2_7_1', 'p_2_7_2', 'p_2_7_3',
                                  name='reason_type_enum'),
                    nullable=False,
                    postgresql_using='type::reason_type_enum')
    op.alter_column('reasons', 'name',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('reasons', 'full_name',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('reasons', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('reasons_company_id_fkey',
                       'reasons', type_='foreignkey')
    op.create_foreign_key(None, 'reasons', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('registry_numbers', 'method_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_constraint('registry_numbers_method_id_fkey',
                       'registry_numbers', type_='foreignkey')
    op.drop_constraint('registry_numbers_company_id_fkey',
                       'registry_numbers', type_='foreignkey')
    op.create_foreign_key(None, 'registry_numbers', 'methods', [
                          'method_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'registry_numbers', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('route_additions', 'route_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('route_additions_route_id_fkey',
                       'route_additions', type_='foreignkey')
    op.create_foreign_key(None, 'route_additions', 'routes', [
                          'route_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('route_employee_assignment_route_id_fkey',
                       'route_employee_assignment', type_='foreignkey')
    op.drop_constraint('route_employee_assignment_employee_id_fkey',
                       'route_employee_assignment', type_='foreignkey')
    op.create_foreign_key(None, 'route_employee_assignment', 'routes', [
                          'route_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'route_employee_assignment', 'employees', [
                          'employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('route_statistic_route_id_fkey',
                       'route_statistic', type_='foreignkey')
    op.create_foreign_key(None, 'route_statistic', 'routes', [
                          'route_id'], ['id'], ondelete='CASCADE')
    op.alter_column('routes', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('routes_company_id_fkey', 'routes', type_='foreignkey')
    op.create_foreign_key(None, 'routes', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('series', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('series_company_id_fkey', 'series', type_='foreignkey')
    op.create_foreign_key(None, 'series', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('si_modifications', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('si_modifications_company_id_fkey',
                       'si_modifications', type_='foreignkey')
    op.create_foreign_key(None, 'si_modifications', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('teams', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('teams_company_id_fkey', 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('verification_entries', 'end_verification_date',
                    existing_type=sa.DATE(),
                    nullable=False)
    op.alter_column('verification_entries', 'verification_date',
                    existing_type=sa.DATE(),
                    nullable=False)
    op.alter_column('verification_entries', 'interval',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('verification_entries', 'manufacture_year',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('verification_entries', 'water_type',
                    existing_type=sa.TEXT(),
                    type_=sa.Enum(
                        'cold', 'hot', name='verification_water_type_enum'),
                    nullable=False,
                    postgresql_using='water_type::verification_water_type_enum')
    op.alter_column('verification_entries', 'meter_info',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('verification_entries', 'seal',
                    existing_type=sa.VARCHAR(length=30),
                    type_=sa.Enum('present', 'damaged', 'missing',
                                  name='verification_seal_enum'),
                    nullable=False,
                    postgresql_using='seal::verification_seal_enum')
    op.alter_column('verification_entries', 'legal_entity',
                    existing_type=sa.TEXT(),
                    type_=sa.Enum('individual', 'legal',
                                  name='verification_legal_entity_enum'),
                    nullable=False,
                    postgresql_using='legal_entity::verification_legal_entity_enum')
    op.drop_constraint('verification_entries_employee_id_fkey',
                       'verification_entries', type_='foreignkey')
    op.drop_constraint('verification_entries_method_id_fkey',
                       'verification_entries', type_='foreignkey')
    op.drop_constraint('verification_entries_company_id_fkey',
                       'verification_entries', type_='foreignkey')
    op.drop_constraint('verification_entries_modification_id_fkey',
                       'verification_entries', type_='foreignkey')
    op.drop_constraint('verification_entries_act_number_id_fkey',
                       'verification_entries', type_='foreignkey')
    op.drop_constraint('verification_entries_city_id_fkey',
                       'verification_entries', type_='foreignkey')
    op.drop_constraint('verification_entries_verifier_id_fkey',
                       'verification_entries', type_='foreignkey')
    op.drop_constraint('verification_entries_registry_number_id_fkey',
                       'verification_entries', type_='foreignkey')
    op.drop_constraint('verification_entries_location_id_fkey',
                       'verification_entries', type_='foreignkey')
    op.drop_constraint('verification_entries_series_id_fkey',
                       'verification_entries', type_='foreignkey')
    op.drop_constraint('verification_entries_reason_id_fkey',
                       'verification_entries', type_='foreignkey')
    op.create_foreign_key(None, 'verification_entries', 'locations', [
                          'location_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'verification_entries', 'series', [
                          'series_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'verification_entries', 'act_numbers', [
                          'act_number_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'verification_entries', 'verifiers', [
                          'verifier_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'verification_entries', 'employees', [
                          'employee_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'verification_entries', 'registry_numbers', [
                          'registry_number_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'verification_entries', 'methods', [
                          'method_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'verification_entries', 'reasons', [
                          'reason_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'verification_entries', 'si_modifications', [
                          'modification_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'verification_entries', 'cities', [
                          'city_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'verification_entries', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('verification_entries_equipments', 'verification_entry_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('verification_entries_equipments', 'equipment_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('verification_entry_photos', 'verification_entry_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('verification_entry_photos_verification_entry_id_fkey',
                       'verification_entry_photos', type_='foreignkey')
    op.create_foreign_key(None, 'verification_entry_photos', 'verification_entries', [
                          'verification_entry_id'], ['id'], ondelete='CASCADE')
    op.alter_column('verification_logs', 'verification_date',
                    existing_type=sa.DATE(),
                    nullable=False)
    op.alter_column('verification_logs', 'verification_limit',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('verification_logs', 'verifier_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('verification_logs_verifier_id_fkey',
                       'verification_logs', type_='foreignkey')
    op.create_foreign_key(None, 'verification_logs', 'verifiers', [
                          'verifier_id'], ['id'], ondelete='CASCADE')
    op.alter_column('verifier_equipment_history', 'action',
                    existing_type=sa.VARCHAR(length=50),
                    type_=sa.Enum(
                        'accepted', 'declined', name='verifier_equipment_action_enum', native_enum=False),
                    existing_nullable=False,
                    postgresql_using='action::verifier_equipment_action_enum')
    op.drop_index('idx_verifier_equipment_history_equipment_id',
                  table_name='verifier_equipment_history')
    op.drop_index('idx_verifier_equipment_history_verifier_id',
                  table_name='verifier_equipment_history')
    op.drop_index('idx_verifier_equipment_unique',
                  table_name='verifier_equipment_history')
    op.create_index(op.f('ix_verifier_equipment_history_id'),
                    'verifier_equipment_history', ['id'], unique=False)
    op.alter_column('verifiers', 'patronymic',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=True)
    op.alter_column('verifiers', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('verifiers_team_id_fkey',
                       'verifiers', type_='foreignkey')
    op.drop_constraint('verifiers_company_id_fkey',
                       'verifiers', type_='foreignkey')
    op.create_foreign_key(None, 'verifiers', 'teams', [
                          'team_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'verifiers', 'companies', [
                          'company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verifiers', type_='foreignkey')
    op.drop_constraint(None, 'verifiers', type_='foreignkey')
    op.create_foreign_key('verifiers_company_id_fkey',
                          'verifiers', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('verifiers_team_id_fkey',
                          'verifiers', 'teams', ['team_id'], ['id'])
    op.alter_column('verifiers', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('verifiers', 'patronymic',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=False)
    op.drop_index(op.f('ix_verifier_equipment_history_id'),
                  table_name='verifier_equipment_history')
    op.create_index('idx_verifier_equipment_unique', 'verifier_equipment_history', [
                    'verifier_id', 'equipment_id'], unique=True)
    op.create_index('idx_verifier_equipment_history_verifier_id',
                    'verifier_equipment_history', ['verifier_id'], unique=False)
    op.create_index('idx_verifier_equipment_history_equipment_id',
                    'verifier_equipment_history', ['equipment_id'], unique=False)
    op.alter_column('verifier_equipment_history', 'action',
                    existing_type=sa.Enum(
                        'accepted', 'declined', name='verifier_equipment_action_enum', native_enum=False),
                    type_=sa.VARCHAR(length=50),
                    existing_nullable=False,)
    op.drop_constraint(None, 'verification_logs', type_='foreignkey')
    op.create_foreign_key('verification_logs_verifier_id_fkey',
                          'verification_logs', 'verifiers', ['verifier_id'], ['id'])
    op.alter_column('verification_logs', 'verifier_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('verification_logs', 'verification_limit',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('verification_logs', 'verification_date',
                    existing_type=sa.DATE(),
                    nullable=True)
    op.drop_constraint(None, 'verification_entry_photos', type_='foreignkey')
    op.create_foreign_key('verification_entry_photos_verification_entry_id_fkey',
                          'verification_entry_photos', 'verification_entries', ['verification_entry_id'], ['id'])
    op.alter_column('verification_entry_photos', 'verification_entry_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('verification_entries_equipments', 'equipment_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('verification_entries_equipments', 'verification_entry_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_constraint(None, 'verification_entries', type_='foreignkey')
    op.drop_constraint(None, 'verification_entries', type_='foreignkey')
    op.drop_constraint(None, 'verification_entries', type_='foreignkey')
    op.drop_constraint(None, 'verification_entries', type_='foreignkey')
    op.drop_constraint(None, 'verification_entries', type_='foreignkey')
    op.drop_constraint(None, 'verification_entries', type_='foreignkey')
    op.drop_constraint(None, 'verification_entries', type_='foreignkey')
    op.drop_constraint(None, 'verification_entries', type_='foreignkey')
    op.drop_constraint(None, 'verification_entries', type_='foreignkey')
    op.drop_constraint(None, 'verification_entries', type_='foreignkey')
    op.drop_constraint(None, 'verification_entries', type_='foreignkey')
    op.create_foreign_key('verification_entries_reason_id_fkey',
                          'verification_entries', 'reasons', ['reason_id'], ['id'])
    op.create_foreign_key('verification_entries_series_id_fkey',
                          'verification_entries', 'series', ['series_id'], ['id'])
    op.create_foreign_key('verification_entries_location_id_fkey',
                          'verification_entries', 'locations', ['location_id'], ['id'])
    op.create_foreign_key('verification_entries_registry_number_id_fkey',
                          'verification_entries', 'registry_numbers', ['registry_number_id'], ['id'])
    op.create_foreign_key('verification_entries_verifier_id_fkey',
                          'verification_entries', 'verifiers', ['verifier_id'], ['id'])
    op.create_foreign_key('verification_entries_city_id_fkey',
                          'verification_entries', 'cities', ['city_id'], ['id'])
    op.create_foreign_key('verification_entries_act_number_id_fkey',
                          'verification_entries', 'act_numbers', ['act_number_id'], ['id'])
    op.create_foreign_key('verification_entries_modification_id_fkey',
                          'verification_entries', 'si_modifications', ['modification_id'], ['id'])
    op.create_foreign_key('verification_entries_company_id_fkey',
                          'verification_entries', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('verification_entries_method_id_fkey',
                          'verification_entries', 'methods', ['method_id'], ['id'])
    op.create_foreign_key('verification_entries_employee_id_fkey',
                          'verification_entries', 'employees', ['employee_id'], ['id'])
    op.alter_column('verification_entries', 'legal_entity',
                    existing_type=sa.Enum(
                        'individual', 'legal', name='verification_legal_entity_enum'),
                    type_=sa.TEXT(),
                    nullable=True)
    op.alter_column('verification_entries', 'seal',
                    existing_type=sa.Enum(
                        'present', 'damaged', 'missing', name='verification_seal_enum'),
                    type_=sa.VARCHAR(length=30),
                    nullable=True)
    op.alter_column('verification_entries', 'meter_info',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('verification_entries', 'water_type',
                    existing_type=sa.Enum(
                        'cold', 'hot', name='verification_water_type_enum'),
                    type_=sa.TEXT(),
                    nullable=True)
    op.alter_column('verification_entries', 'manufacture_year',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('verification_entries', 'interval',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('verification_entries', 'verification_date',
                    existing_type=sa.DATE(),
                    nullable=True)
    op.alter_column('verification_entries', 'end_verification_date',
                    existing_type=sa.DATE(),
                    nullable=True)
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key('teams_company_id_fkey', 'teams',
                          'companies', ['company_id'], ['id'])
    op.alter_column('teams', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_constraint(None, 'si_modifications', type_='foreignkey')
    op.create_foreign_key('si_modifications_company_id_fkey',
                          'si_modifications', 'companies', ['company_id'], ['id'])
    op.alter_column('si_modifications', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.create_foreign_key('series_company_id_fkey', 'series',
                          'companies', ['company_id'], ['id'])
    op.alter_column('series', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.create_foreign_key('routes_company_id_fkey', 'routes',
                          'companies', ['company_id'], ['id'])
    op.alter_column('routes', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_constraint(None, 'route_statistic', type_='foreignkey')
    op.create_foreign_key('route_statistic_route_id_fkey',
                          'route_statistic', 'routes', ['route_id'], ['id'])
    op.drop_constraint(None, 'route_employee_assignment', type_='foreignkey')
    op.drop_constraint(None, 'route_employee_assignment', type_='foreignkey')
    op.create_foreign_key('route_employee_assignment_employee_id_fkey',
                          'route_employee_assignment', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key('route_employee_assignment_route_id_fkey',
                          'route_employee_assignment', 'routes', ['route_id'], ['id'])
    op.drop_constraint(None, 'route_additions', type_='foreignkey')
    op.create_foreign_key('route_additions_route_id_fkey',
                          'route_additions', 'routes', ['route_id'], ['id'])
    op.alter_column('route_additions', 'route_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_constraint(None, 'registry_numbers', type_='foreignkey')
    op.drop_constraint(None, 'registry_numbers', type_='foreignkey')
    op.create_foreign_key('registry_numbers_company_id_fkey',
                          'registry_numbers', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('registry_numbers_method_id_fkey',
                          'registry_numbers', 'methods', ['method_id'], ['id'])
    op.alter_column('registry_numbers', 'method_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint(None, 'reasons', type_='foreignkey')
    op.create_foreign_key('reasons_company_id_fkey',
                          'reasons', 'companies', ['company_id'], ['id'])
    op.alter_column('reasons', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('reasons', 'full_name',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('reasons', 'name',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('reasons', 'type',
                    existing_type=sa.Enum(
                        'p_2_7_1', 'p_2_7_2', 'p_2_7_3', name='reason_type_enum'),
                    type_=sa.VARCHAR(length=20),
                    nullable=True)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_route_id_fkey', 'orders',
                          'routes', ['route_id'], ['id'])
    op.create_foreign_key('orders_city_id_fkey', 'orders',
                          'cities', ['city_id'], ['id'])
    op.create_foreign_key('orders_dispatcher_id_fkey',
                          'orders', 'employees', ['dispatcher_id'], ['id'])
    op.create_foreign_key('orders_company_id_fkey', 'orders',
                          'companies', ['company_id'], ['id'])
    op.alter_column('orders', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('orders', 'status',
                    existing_type=sa.Enum(
                        'pending', 'approved', name='order_status_enum'),
                    type_=sa.TEXT(),
                    nullable=True)
    op.alter_column('orders', 'water_type',
                    existing_type=sa.Enum(
                        'cold', 'hot', 'cold_hot', 'unnamed', name='order_water_type_enum'),
                    type_=sa.VARCHAR(length=30),
                    nullable=True)
    op.alter_column('orders', 'counter_number',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('orders', 'legal_entity',
                    existing_type=sa.Enum(
                        'individual', 'legal', name='verification_legal_entity_enum'),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.alter_column('orders', 'phone_number',
                    existing_type=sa.VARCHAR(length=18),
                    nullable=True)
    op.alter_column('orders', 'address',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.add_column('metrologs_info', sa.Column('befor_humdity', sa.DOUBLE_PRECISION(
        precision=53), autoincrement=False, nullable=True))
    op.add_column('metrologs_info', sa.Column('befor_pressure',
                  sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('metrologs_info', sa.Column('befor_water_temperature',
                  sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('metrologs_info', sa.Column('befor_air_temperature',
                  sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'metrologs_info', type_='foreignkey')
    op.create_foreign_key('fk_metrologs_info_company',
                          'metrologs_info', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('metrologs_info_verification_id_fkey',
                          'metrologs_info', 'verification_entries', ['verification_id'], ['id'])
    op.alter_column('metrologs_info', 'company_id',
                    existing_type=sa.Integer(),
                    type_=sa.BIGINT(),
                    existing_nullable=False)
    op.alter_column('metrologs_info', 'verification_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_column('metrologs_info', 'before_pressure')
    op.drop_column('metrologs_info', 'before_humdity')
    op.drop_column('metrologs_info', 'before_air_temperature')
    op.drop_column('metrologs_info', 'before_water_temperature')
    op.drop_constraint(None, 'methods', type_='foreignkey')
    op.create_foreign_key('methods_company_id_fkey',
                          'methods', 'companies', ['company_id'], ['id'])
    op.alter_column('methods', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key('locations_company_id_fkey',
                          'locations', 'companies', ['company_id'], ['id'])
    op.alter_column('locations', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('locations', 'count',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('locations', 'name',
                    existing_type=sa.VARCHAR(length=60),
                    nullable=True)
    op.drop_constraint(None, 'equipments_verifiers', type_='foreignkey')
    op.drop_constraint(None, 'equipments_verifiers', type_='foreignkey')
    op.create_foreign_key('equipments_verifiers_equipment_id_fkey',
                          'equipments_verifiers', 'equipments', ['equipment_id'], ['id'])
    op.create_foreign_key('equipments_verifiers_verifier_id_fkey',
                          'equipments_verifiers', 'verifiers', ['verifier_id'], ['id'])
    op.drop_constraint(None, 'equipments', type_='foreignkey')
    op.drop_constraint(None, 'equipments', type_='foreignkey')
    op.drop_constraint(None, 'equipments', type_='foreignkey')
    op.create_foreign_key('equipments_company_id_fkey',
                          'equipments', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('equipments_si_type_id_fkey',
                          'equipments', 'company_si_types', ['si_type_id'], ['id'])
    op.create_foreign_key('equipments_activity_id_fkey', 'equipments',
                          'company_activities', ['activity_id'], ['id'])
    op.alter_column('equipments', 'type',
                    existing_type=sa.Enum(
                        'standard', 'measurement', 'auxiliary', 'other', name='equipment_type_enum'),
                    type_=sa.VARCHAR(length=120),
                    existing_nullable=False)
    op.alter_column('equipment_info', 'date_to',
                    existing_type=sa.DATE(),
                    nullable=True)
    op.alter_column('equipment_info', 'date_from',
                    existing_type=sa.DATE(),
                    nullable=True)
    op.alter_column('equipment_info', 'type',
                    existing_type=sa.Enum(
                        'maintenance', 'verification', name='equipment_info_type_enum'),
                    type_=sa.VARCHAR(length=30),
                    nullable=True)
    op.drop_constraint(None, 'employees_routes', type_='foreignkey')
    op.drop_constraint(None, 'employees_routes', type_='foreignkey')
    op.create_foreign_key('employees_routes_employee_id_fkey',
                          'employees_routes', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key('employees_routes_route_id_fkey',
                          'employees_routes', 'routes', ['route_id'], ['id'])
    op.drop_constraint(None, 'employees_companies', type_='foreignkey')
    op.drop_constraint(None, 'employees_companies', type_='foreignkey')
    op.create_foreign_key('employees_companies_employee_id_fkey',
                          'employees_companies', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key('employees_companies_company_id_fkey',
                          'employees_companies', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'employees_cities', type_='foreignkey')
    op.drop_constraint(None, 'employees_cities', type_='foreignkey')
    op.create_foreign_key('employees_cities_city_id_fkey',
                          'employees_cities', 'cities', ['city_id'], ['id'])
    op.create_foreign_key('employees_cities_employee_id_fkey',
                          'employees_cities', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_series_id_fkey',
                          'employees', 'series', ['series_id'], ['id'])
    op.create_foreign_key('employees_default_verifier_id_fkey',
                          'employees', 'verifiers', ['default_verifier_id'], ['id'])
    op.create_foreign_key('employees_default_city_id_fkey',
                          'employees', 'cities', ['default_city_id'], ['id'])
    op.alter_column('employees', 'status',
                    existing_type=sa.Enum('admin', 'director', 'auditor', 'dispatcher1',
                                          'dispatcher2', 'verifier', name='employee_status_enum'),
                    type_=sa.VARCHAR(length=30),
                    existing_nullable=False)
    op.drop_constraint(None, 'counter_assignments', type_='foreignkey')
    op.drop_constraint(None, 'counter_assignments', type_='foreignkey')
    op.create_foreign_key('counter_assignments_employee_id_fkey',
                          'counter_assignments', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key('counter_assignments_order_id_fkey',
                          'counter_assignments', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'company_si_types', type_='foreignkey')
    op.create_foreign_key('company_si_types_company_id_fkey',
                          'company_si_types', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_company_si_types_id'),
                  table_name='company_si_types')
    op.add_column('company_reports', sa.Column(
        'is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'company_reports', type_='foreignkey')
    op.create_foreign_key('company_reports_company_id_fkey',
                          'company_reports', 'companies', ['company_id'], ['id'])
    op.alter_column('company_reports', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('company_reports', 'name',
                    existing_type=sa.String(length=100),
                    type_=sa.VARCHAR(length=60),
                    nullable=True)
    op.drop_column('company_reports', 'fields_order')
    op.drop_constraint(None, 'company_calendar_day_info', type_='foreignkey')
    op.create_foreign_key('company_calendar_day_info_company_id_fkey',
                          'company_calendar_day_info', 'companies', ['company_id'], ['id'])
    op.alter_column('company_calendar_day_info', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_constraint(None, 'company_activities', type_='foreignkey')
    op.create_foreign_key('company_activities_company_id_fkey',
                          'company_activities', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_company_activities_id'),
                  table_name='company_activities')
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.create_foreign_key('cities_company_id_fkey', 'cities',
                          'companies', ['company_id'], ['id'])
    op.alter_column('cities', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_constraint(None, 'appeals', type_='foreignkey')
    op.drop_constraint(None, 'appeals', type_='foreignkey')
    op.create_foreign_key('appeals_dispatcher_id_fkey',
                          'appeals', 'employees', ['dispatcher_id'], ['id'])
    op.create_foreign_key('appeals_company_id_fkey',
                          'appeals', 'companies', ['company_id'], ['id'])
    op.alter_column('appeals', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('appeals', 'status',
                    existing_type=sa.Enum(
                        'accepted', 'in_progress', 'done', name='appeal_status_enum'),
                    type_=sa.TEXT(),
                    nullable=True)
    op.drop_constraint(None, 'act_numbers', type_='foreignkey')
    op.drop_constraint(None, 'act_numbers', type_='foreignkey')
    op.drop_constraint(None, 'act_numbers', type_='foreignkey')
    op.create_foreign_key('act_numbers_company_id_fkey',
                          'act_numbers', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('act_numbers_series_id_fkey',
                          'act_numbers', 'series', ['series_id'], ['id'])
    op.create_foreign_key('act_numbers_city_id_fkey',
                          'act_numbers', 'cities', ['city_id'], ['id'])
    op.drop_constraint('uq_act_number_company_series',
                       'act_numbers', type_='unique')
    op.alter_column('act_numbers', 'company_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('act_numbers', 'count',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('act_numbers', 'legal_entity',
                    existing_type=sa.Enum(
                        'individual', 'legal', name='verification_legal_entity_enum'),
                    type_=sa.TEXT(),
                    nullable=True)
    op.alter_column('act_numbers', 'verification_date',
                    existing_type=sa.DATE(),
                    nullable=True)
    op.alter_column('act_numbers', 'address',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('act_numbers', 'act_number',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_index(op.f('ix_company_tariff_state_last_tariff_history_id'),
                  table_name='company_tariff_state')
    op.drop_index(op.f('ix_company_tariff_state_id'),
                  table_name='company_tariff_state')
    op.drop_index(op.f('ix_company_tariff_state_company_id'),
                  table_name='company_tariff_state')
    op.drop_table('company_tariff_state')
    op.drop_index(op.f('ix_company_tariff_history_is_active'),
                  table_name='company_tariff_history')
    op.drop_index(op.f('ix_company_tariff_history_id'),
                  table_name='company_tariff_history')
    op.drop_index(op.f('ix_company_tariff_history_created_at'),
                  table_name='company_tariff_history')
    op.drop_index(op.f('ix_company_tariff_history_company_id'),
                  table_name='company_tariff_history')
    op.drop_table('company_tariff_history')
    op.drop_index(op.f('ix_calendar_reports_id'),
                  table_name='calendar_reports')
    op.drop_table('calendar_reports')
    op.drop_index(op.f('ix_base_tariff_plans_id'),
                  table_name='base_tariff_plans')
    op.drop_table('base_tariff_plans')
    # ### end Alembic commands ###
